HELLO EVERYONE WELCOME TO PYTHON

In [210]:
import numpy as np
import pandas as pd

In [211]:
# reading the csv file and converting it into dataframe
df = pd.read_csv("C:/Users/SAIKAT/Downloads/employees_100 (1).csv")

# getting the information about the data frame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 11.8 KB

In [212]:
# getting na values from each column
df.isna().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [213]:
# getting the sample of the data 
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [214]:
# fixing the na values if city ,age and salary
df['department'] = df['department'].str.strip().str.lower()
df['city'] = df['city'].fillna(df['city'].mode()[0])
df['department'] = df['department'].fillna(df['department'].mode()[0])
df['age']= df['age'].fillna(df['age'].mean())
df['age'] = df['age'].astype(int)
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['salary'] = df['salary'].fillna(df['salary'].mean())
df['salary'] = df['salary'].astype(int)

df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [215]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          100 non-null    str
 3   city                100 non-null    str
 4   age                 100 non-null    int64
 5   salary              100 non-null    int64
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: int64(6), str(4)
memory usage: 11.4 KB

In [216]:
# getting total number of duplicate rows
df.duplicated().sum()

np.int64(0)

In [217]:
# finding duplicate employee_id
df.duplicated(subset=['employee_id']).sum()

np.int64(4)

In [218]:
# fixing duplicate employee_id
df = df.drop_duplicates(subset=['employee_id'], keep='first')
df.duplicated(subset=['employee_id']).sum()

np.int64(0)

In [219]:
# changing the datatype of joining_date column from str to datatime64
df['joining_date'] = pd.to_datetime(df['joining_date'])
df.info()

<class 'pandas.DataFrame'>
Index: 96 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         96 non-null     int64
 1   name                96 non-null     str
 2   department          96 non-null     str
 3   city                96 non-null     str
 4   age                 96 non-null     int64
 5   salary              96 non-null     int64
 6   experience          96 non-null     int64
 7   performance_score   96 non-null     int64
 8   projects_completed  96 non-null     int64
 9   joining_date        96 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(6), str(3)
memory usage: 10.7 KB

In [220]:
# renaming the column names
df.rename(columns={'employee_id' : 'emp_id', 'experience' :"exp", 'department': 'dept','performance_score' : 'perf_score','name':'emp_name'},inplace=True)
df.head()

,emp_id,emp_name,dept,city,age,salary,exp,perf_score,projects_completed,joining_date
0,184,Swati Kapoor,data science,Kolkata,38,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,30,77058,1,8,8,2024-02-05
2,171,Manish Desai,data science,Hyderabad,23,69911,0,6,18,2019-04-24
3,146,Neha Das,engineering,Pune,28,69993,3,8,1,2022-12-13
4,145,Isha Nair,data science,Hyderabad,32,88216,8,8,14,2019-11-25

In [221]:
# fixing column name structure
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns.values

<ArrowStringArray>
[            'emp_id',           'emp_name',               'dept',
               'city',                'age',             'salary',
                'exp',         'perf_score', 'projects_completed',
       'joining_date']
Length: 10, dtype: str

In [222]:
# modifing and creating new columns (feature engineering)
df['annual_salary'] = df['salary'] * 12
def perf_category(perf):
    if perf >=8:
        return "Excellent"
    elif perf >=6:
        return "Good"
    else:
        return "Needs Improvement"

def categorize(num):
    if num > 5:
        return "Experienced"
    elif num <= 5:
        return "Learner"
    
df['perf_category'] = df['perf_score'].apply(perf_category)
df['experience_category'] = df['exp'].apply(categorize)
department_codes = {'data science': 'DS', 'engineering': 'ENG', 'marketing': 'MKT' ,'Finance': 'FIN', 'sales' : "SAL"}
df['department_code'] = df['dept'].map(department_codes)

df.head()

,emp_id,emp_name,dept,city,age,salary,exp,perf_score,projects_completed,joining_date,annual_salary,perf_category,experience_category,department_code
0,184,Swati Kapoor,data science,Kolkata,38,70719,5,5,6,2021-07-02,848628,Needs Improvement,Learner,DS
1,154,Kavya Malhotra,engineering,Mumbai,30,77058,1,8,8,2024-02-05,924696,Excellent,Learner,ENG
2,171,Manish Desai,data science,Hyderabad,23,69911,0,6,18,2019-04-24,838932,Good,Learner,DS
3,146,Neha Das,engineering,Pune,28,69993,3,8,1,2022-12-13,839916,Excellent,Learner,ENG
4,145,Isha Nair,data science,Hyderabad,32,88216,8,8,14,2019-11-25,1058592,Excellent,Experienced,DS

In [223]:
# sorting and ranking
by_emp_id_sorted = df.sort_values(by='emp_id')
by_salary_sorted = df.sort_values(by='salary',ascending=False)
by_department_salary_sorted = df.sort_values(
    by=['dept','salary'],
    ascending = [True, False])

df['salary_rank'] = df['salary'].rank(ascending=False)
df.head(6)

,emp_id,emp_name,dept,city,age,salary,exp,perf_score,projects_completed,joining_date,annual_salary,perf_category,experience_category,department_code,salary_rank
0,184,Swati Kapoor,data science,Kolkata,38,70719,5,5,6,2021-07-02,848628,Needs Improvement,Learner,DS,22.0
1,154,Kavya Malhotra,engineering,Mumbai,30,77058,1,8,8,2024-02-05,924696,Excellent,Learner,ENG,12.0
2,171,Manish Desai,data science,Hyderabad,23,69911,0,6,18,2019-04-24,838932,Good,Learner,DS,24.0
3,146,Neha Das,engineering,Pune,28,69993,3,8,1,2022-12-13,839916,Excellent,Learner,ENG,23.0
4,145,Isha Nair,data science,Hyderabad,32,88216,8,8,14,2019-11-25,1058592,Excellent,Experienced,DS,1.0
5,140,Rahul Gupta,sales,Hyderabad,23,52404,0,9,13,2018-12-27,628848,Excellent,Learner,SAL,90.0

In [ ]:
# grouping and aggregation
dept_city_salary_groupby = df.groupby(['dept','city'])[['salary']].mean()
dept_salary_perfscore_empid_groupby = df.groupby('dept').agg({
    'salary' : ["mean", "max"],
    'perf_score' : 'mean',
    'emp_id' : 'count'
})
department_summary = df.groupby('dept').agg(
    average_salary = ('salary', 'mean'),
    highest_salary = ('salary', 'max'),
    employee_count = ('emp_id', 'count')
)
department_summary

              average_salary  highest_salary  employee_count
dept
data science    75646.500000           88216              10
engineering     73688.058824           84870              17
finance         65770.294118           80597              17
hr              59826.750000           74505              24
marketing       59716.368421           69499              19
sales           59726.666667           68490               9

,emp_id,emp_name,dept,city,age,salary,exp,perf_score,projects_completed,joining_date,annual_salary,perf_category,experience_category,department_code,salary_rank
0,184,Swati Kapoor,data science,Kolkata,38,70719,5,5,6,2021-07-02,848628,Needs Improvement,Learner,DS,22.0
1,154,Kavya Malhotra,engineering,Mumbai,30,77058,1,8,8,2024-02-05,924696,Excellent,Learner,ENG,12.0
2,171,Manish Desai,data science,Hyderabad,23,69911,0,6,18,2019-04-24,838932,Good,Learner,DS,24.0
3,146,Neha Das,engineering,Pune,28,69993,3,8,1,2022-12-13,839916,Excellent,Learner,ENG,23.0
4,145,Isha Nair,data science,Hyderabad,32,88216,8,8,14,2019-11-25,1058592,Excellent,Experienced,DS,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,marketing,Chennai,22,55740,0,5,22,2020-04-22,668880,Needs Improvement,Learner,MKT,84.0
96,172,Neha Desai,hr,Chennai,22,52250,0,5,7,2020-11-14,627000,Needs Improvement,Learner,NaN,91.0
97,115,Neha Reddy,marketing,Chennai,43,64819,12,4,10,2019-06-06,777828,Needs Improvement,Experienced,MKT,44.5
98,193,Priya Nayak,hr,Hyderabad,23,56821,3,9,16,2019-08-07,681852,Excellent,Learner,NaN,78.0
99,152,Kavya Joshi,marketing,Delhi,44,69499,10,7,4,2022-03-25,833988,Good,Experienced,MKT,26.0